# Generated by Django 4.1.7 on 2023-03-01 20:10

from django.db import migrations


def create_groups(apps, schema_migration):
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')

    managers = Group(name='MANAGER')
    managers.save()

    sales = Group(name='SALES')
    sales.save()

    supports = Group(name='SUPPORT')
    supports.save()

    for user in User.objects.all():
        if user.groups == 'MANAGER':
            managers.user_set.add(user)


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_groups)
    ]
