# Generated by Django 4.1.7 on 2023-03-01 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='sales_contact',
        ),
        migrations.AddField(
            model_name='contract',
            name='event_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crmapi.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.IntegerField(choices=[(0, 'In Development'), (1, 'Waiting Customer'), (2, 'Action Required'), (3, 'Terminated'), (4, 'Cancelled')], default=0, verbose_name='Event status'),
        ),
        migrations.DeleteModel(
            name='ContractStatus',
        ),
    ]
