# Generated by Django 4.1.7 on 2023-03-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapi', '0004_alter_event_event_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='event_id',
            new_name='event',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.IntegerField(choices=[(0, 'In Development'), (1, 'Waiting Customer'), (2, 'Action Required'), (3, 'Terminated'), (4, 'Cancelled')], default=0, verbose_name='Event status'),
        ),
    ]
