# Generated by Django 4.1.7 on 2023-03-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapi', '0010_alter_event_event_status_alter_event_support_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='payment_due',
            field=models.DateField(blank=True, null=True, verbose_name='Date of payment'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.IntegerField(choices=[(0, 'In Development'), (1, 'Waiting Customer'), (2, 'Action Required'), (3, 'Terminated'), (4, 'Cancelled')], default=0, verbose_name='Event status'),
        ),
    ]
