# Generated by Django 4.1.7 on 2023-03-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapi', '0012_alter_event_event_date_alter_event_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(blank=True, default='0', verbose_name='Attendees'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, default='1900-01-01', verbose_name='Event date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.IntegerField(choices=[(0, 'In Development'), (1, 'Waiting Customer'), (2, 'Action Required'), (3, 'Terminated'), (4, 'Cancelled')], default=0, verbose_name='Event status'),
        ),
    ]
