# Generated by Django 4.1.7 on 2023-03-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapi', '0014_alter_event_event_date_alter_event_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='company_name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Compagny name'),
        ),
    ]
