# Generated by Django 4.1.7 on 2023-04-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crmapi', '0015_alter_client_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Amount'),
        ),
    ]
