# Generated by Django 4.1.7 on 2023-06-01 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crmapi', '0019_alter_contract_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract_event', to='crmapi.event', verbose_name='Event'),
        ),
    ]
